# Generated by Django 3.0.8 on 2020-07-25 10:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='table_name',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('integer_field', models.IntegerField()),
                ('char_field', models.CharField(max_length=50)),
                ('textarea_field', models.TextField()),
            ],
        ),
    ]
